### ISSUE TITLE
Elixir 1.4 - mix compile fails

### ISSUE THREAD

**Issue by fnchooft** [travelping/hello#102]
I was trying to compile with mix on elixir 1.4, but there seems to be an error with the lager-configuration in the mix-case.

Using rebar3 ( following the .travis.yml commands) the entire package seems to compile fine.

**Comment by umatomba** [comment]
Hi @fnchooft, elixir 1.4 has a bug in mix. https://github.com/elixir-lang/elixir/issues/5640
Try with elixir 1.4.1

**Comment by fnchooft** [comment]
Will do - thanks for the tip.
