### ISSUE TITLE
[http][json-rpc] spaces brokes the request

### ISSUE THREAD

**Issue by liveforeverx** [travelping/hello#20]
If somebody tries to send as payload something started with spaces, for example: `  {"json...}` it crashes a server.

**Comment by surik** [comment]
I could not reproduce it. Do you have an example? 
I send this json: ```<<"   {\"id\":1,\"params\":[],\"method\":\"Test.try\",\"jsonrpc\":\"2.0\"}">>``` and it works correct.

**Comment by liveforeverx** [comment]
curl -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d '  {"id": "1", "jsonrpc": "2.0", "method":"Server.ping", "params": {} }' http://127.0.0.1:26000

If you start (hello_ping_pong)[https://github.com/liveforeverx/hello_pingpong] on http.
