### ISSUE TITLE
May be update to rebar3 with hex dependencies?

### ISSUE THREAD

**Issue by liveforeverx** [travelping/hello#22]

**Comment by liveforeverx** [comment]
Alternative we can add mix.exs for hex dependencies on elixir applications

**Comment by liveforeverx** [comment]
cowboy update: hexpm/community#57

**Comment by surik** [comment]
For rebar3 we need to support next dependencies:
- [ ] dnssd benoitc/dnssd_erlang/pull/11
- [ ] yang
- [ ] yang compiler plugin
- [ ] ex_uri (abnf compiler)

**Comment by surik** [comment]
rebar3 and mix are supported
