### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by skattelmann** [travelping/hello#66]
currently 'hello' has no proper logging. The 'hello_handler' already has some nice logging stuff build in but this is quite obviously not enough. At least the client, server and transport modules should log in a sophisticated way.

**Comment by hwinkel** [comment]
@skattelmann in scope of a public application there is no reason to make a statement of the current logging sate of other applications.

**Comment by GalaxyGorilla** [comment]
I agree, therefore I decreased the log levels of almost all logs to debug. Atm hello is spamming log backends without value for anyone. The PR 69 is basically about fixing this. Additionaly the changes I made there do help a lot in a debugging context.
